### PR TITLE
Run Chrome headless

### LINKED ISSUE #17: Missing Chrome headless flag?
Tool started failing in CI - would that be because you don't specify `--chrome-flags="--headless"` in the Lighthouse command?

### PR DESCRIPTION
**Pull request by elsassph**
Fixes #17

### CODE REVIEW

**Comment by mikestead** [comment]
Thanks @elsassph.

Question, do we need the `--no-sandbox` and `--disable-gpu` flags too? The recent docs seem to just use `--headless`? Oh actually there is a `--no-sandbox` for ubuntu documented. Just checking before we merge.

https://github.com/GoogleChrome/lighthouse/blob/master/docs/headless-chrome.md

**Comment by elsassph** [comment]
That's the example flags in the lighthouse doc, if I remember correctly.

**Comment by elsassph** [comment]
https://github.com/GoogleChrome/lighthouse/blob/master/readme.md#run

That's the flag they mention in case of problems connecting to Chrome.

**Comment by mikestead** [comment]
It would be useful it they stated why these flags are needed and what impact they have if any on the results.

I did find this ticket https://github.com/theintern/intern/issues/878 around `--no-sandbox` so assume it's about running inside containers without a user defined. Not sure that's great though for other circumstances, or if it impacts results.

The `--disable-gpu` seems to [impact webGL](https://github.com/GoogleChrome/puppeteer/issues/1260) features which may be a problem for some sites. There's a confusing history around what that flag is needed for and on which platforms.

Anyway without a great amount of details (or time) at hand I do know this fixes some other things up so I'll release under a major bump and if we run into any issues we can address those later.

**Comment by mikestead** [comment]
Released under `v4.0.0`, cheers @elsassph

**Pull request merged**
